global:
  scrape_interval: 5s
  scrape_timeout: 3s

  external_labels:
    monitor: 'fastcampus-monitoring'
  query_log_file: query_log_file.log

scrape_configs:
  - job_name: 'fastcampus-featureflag'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'

    static_configs:
      - targets: ['featureflag-service:9292']
